# Generated by Django 4.2 on 2023-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Agent of register"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP of register"
            ),
        ),
    ]
