# Generated by Django 4.2 on 2023-07-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_agent_user_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="disabled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Disabled at"
            ),
        ),
    ]
