# Generated by Django 4.2 on 2023-07-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_disabled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="disable_agent",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Agent of disable"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="disable_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP of disable"
            ),
        ),
    ]
