# Generated by Django 4.2 on 2023-07-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_disable_agent_user_disable_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="disable_email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email of disable"
            ),
        ),
    ]
