# Generated by Django 4.2 on 2023-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
            },
        ),
        migrations.AlterField(
            model_name="expense",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pendente"),
                    ("overdue", "Vencida"),
                    ("paid", "Pago"),
                ],
                max_length=255,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
