# Generated by Django 4.2 on 2023-06-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_expense_options_alter_expense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(blank=True, choices=[('Others', 'Outros'), ('Home', 'Casa'), ('Vehicles', 'Veículos'), ('Education', 'Educação')], max_length=255, null=True, verbose_name='Status'),
        ),
    ]
