# Generated by Django 4.2 on 2023-06-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0003_expense_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="type_expense",
        ),
        migrations.AlterField(
            model_name="expense",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pendente"),
                    ("overdue", "Vencido"),
                    ("paid", "Pago"),
                ],
                max_length=255,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="type",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expenses",
                to="financial.typeexpense",
                verbose_name="Tipo de Despesa",
            ),
        ),
    ]
